# Deploy Sphinx content to GitHub Pages
name: Docs

on:
  # Runs on pushes targeting the default branch
  workflow_call:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read

jobs:
  build:
    name: Build the documentation with Sphinx
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Install
        uses: pandoc/actions/setup@6a25d32c172975d0c82425964800b60988e93279
        with:
          version: 2.19

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          submodules: recursive

      - run: git fetch origin main

      - name: troubleshooting
        run: |
          git branch
          git remote -v

      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          sudo apt-get install -y doxygen graphviz
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt -r docs/requirements.txt

      - name: Checkout docs root
        run: |
          git clone https://github.com/sandialabs/sansmic-docs.git
          python -m pip install -r sansmic-docs/docs/requirements.txt

      - name: Build documentation
        run: |
          python -m pip install -e .[formats]
          bash sansmic-docs/build-docs.sh

      - name: Checkout old documentation
        run: |
          for TAG in $(cat tagged.txt); do
            pushd sansmic-docs
            git checkout -f $TAG
            cp -rf html ../html/$TAG
            popd
          done

      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        if: success() || failure()
        with:
          path: 'html/'
